import type { Language } from './translations'

const esSteps = [
  ['El punto de partida','Comienza el recorrido: salario, precios y empleo vistos con la misma regla cotidiana.','Regla fiscal y auge minero-energético','La disciplina fiscal buscó limitar déficits, mientras los altos precios de materias primas apoyaban exportaciones e ingresos públicos.','Juan Manuel Santos'],
  ['Un nuevo año para comparar','El salario, la inflación y el empleo se mueven a ritmos diferentes. La cantidad equivalente de Chocorramos permite leerlos en una sola imagen.','TLC con Estados Unidos','Entró en vigor el acuerdo comercial: redujo barreras y amplió mercados, pero también aumentó la competencia para productores nacionales.','Juan Manuel Santos'],
  ['Un nuevo año para comparar','La comparación anual continúa con la misma regla cotidiana.','Infraestructura 4G','El programa de carreteras buscó reducir costos logísticos y atraer inversión. Sus efectos dependen de la ejecución y tardan años en sentirse.','Juan Manuel Santos'],
  ['Un nuevo año para comparar','Salario, precios y empleo responden también a choques internacionales.','Caída del precio del petróleo','El choque externo redujo ingresos de exportación y del Gobierno, y presionó la tasa de cambio. No fue causado por una política nacional.','Juan Manuel Santos'],
  ['Los precios aceleran','La inflación subió con fuerza. Un aumento salarial no significa automáticamente mayor poder de compra.','Petróleo barato y peso más débil','La devaluación encareció importaciones y aportó presión inflacionaria, mientras la economía se ajustaba a menores ingresos petroleros.','Juan Manuel Santos'],
  ['Los precios ganan terreno','La comparación muestra cuánto compra el salario cuando precios e ingresos cambian al mismo tiempo.','Acuerdo de paz','El acuerdo buscó reducir costos del conflicto y ampliar oportunidades rurales. Sus beneficios económicos dependen de una implementación prolongada.','Juan Manuel Santos'],
  ['Un nuevo año para comparar','La cantidad equivalente de Chocorramos resume el movimiento del salario y los precios.','IVA del 19%','La reforma tributaria elevó el IVA general para fortalecer ingresos públicos; también aumentó el costo inmediato de varios consumos gravados.','Juan Manuel Santos'],
  ['Un año compartido','La transición presidencial impide atribuir todo el resultado a una sola administración.','Transición de gobierno','Continuaron proyectos de infraestructura y ajustes fiscales. Es un año compartido entre Santos y Duque.','Transición Santos → Duque'],
  ['Un nuevo año para comparar','Los cambios tributarios y laborales forman parte del contexto, no una explicación única.','Ley de financiamiento','Los cambios tributarios buscaron incentivar inversión y recaudar recursos; sus efectos fueron debatidos.','Iván Duque'],
  ['El golpe al empleo','La tasa de desempleo alcanzó el punto más alto de esta serie. Tener salario también depende de conservar un trabajo.','COVID-19 y confinamientos','La pandemia paralizó actividades, destruyó empleo y exigió gasto de emergencia. Fue un choque mundial.','Iván Duque'],
  ['La recuperación empieza','El desempleo bajó frente a 2020, pero la informalidad comparable seguía cerca de seis de cada diez ocupados.','Reapertura y recuperación','La actividad y el empleo rebotaron, pero persistieron informalidad y desigualdad.','Iván Duque'],
  ['Un millón de pesos','El salario mínimo alcanzó el millón, mientras la inflación cerró en dos dígitos.','Inflación global y transición','Alimentos, energía y cadenas logísticas presionaron la inflación. El año fue compartido entre Duque y Petro.','Transición Duque → Petro'],
  ['El salario responde','El aumento nominal fue fuerte, aunque los precios todavía crecieron rápidamente.','Ajuste de gasolina y reforma tributaria','El ajuste redujo el déficit del fondo de combustibles, pero elevó costos de transporte.','Gustavo Petro'],
  ['Salarios, tasas y reformas','Los ingresos formales aumentan mientras crédito, inversión e informalidad siguen condicionando el resultado.','Salarios, tasas y reformas','Aumentos salariales apoyaron ingresos formales, mientras tasas altas frenaron crédito e inversión.','Gustavo Petro'],
  ['Menos desempleo, informalidad persistente','La tasa de desempleo bajó, pero más de la mitad de las personas ocupadas seguía en la informalidad.','Recuperación con retos fiscales','El consumo y los servicios sostuvieron actividad, pero inversión, informalidad y cuentas públicas siguieron siendo retos.','Gustavo Petro'],
  ['El presente todavía está en movimiento','Los datos de inflación y empleo son parciales. Esta fotografía cambiará cuando cierre el año.','Datos parciales y cambio político','El año todavía no ha cerrado. Salario, inflación, tasas, gasto y expectativas pueden cambiar el resultado final.','Gustavo Petro'],
] as const

const enSteps = [
  ['The starting point','The journey begins: wages, prices and employment viewed through the same everyday yardstick.','Fiscal rule and the commodities boom','Fiscal discipline sought to limit deficits while high commodity prices supported exports and public revenue.','Juan Manuel Santos'],
  ['A new year to compare','Wages, inflation and employment move at different speeds. The Chocorramo equivalent brings them into one image.','US–Colombia Trade Agreement','The agreement reduced barriers and widened markets, while also increasing competition for domestic producers.','Juan Manuel Santos'],
  ['A new year to compare','The annual comparison continues with the same everyday yardstick.','4G infrastructure programme','The road programme sought to reduce logistics costs and attract investment. Its effects depend on execution and take years.','Juan Manuel Santos'],
  ['A new year to compare','Wages, prices and employment also respond to international shocks.','Oil price collapse','The external shock reduced export and government revenue and pressured the exchange rate. It was not caused by domestic policy.','Juan Manuel Santos'],
  ['Prices accelerate','Inflation rose sharply. A wage increase does not automatically mean greater purchasing power.','Cheaper oil and a weaker peso','Depreciation made imports more expensive and added inflationary pressure as the economy adjusted to lower oil income.','Juan Manuel Santos'],
  ['Prices gain ground','The comparison shows what wages buy when prices and income change together.','Peace agreement','The agreement sought to reduce conflict costs and widen rural opportunity. Its benefits depend on long-term implementation.','Juan Manuel Santos'],
  ['A new year to compare','The Chocorramo equivalent summarises the movement of wages and prices.','VAT rises to 19%','The tax reform raised general VAT to strengthen revenue and immediately increased the cost of several taxed purchases.','Juan Manuel Santos'],
  ['A shared year','The presidential transition means the full result cannot be assigned to one administration.','Government transition','Infrastructure projects and fiscal adjustments continued. The year was shared by Santos and Duque.','Santos → Duque transition'],
  ['A new year to compare','Tax and labour changes form part of the context, not a single explanation.','Financing law','Tax changes sought to encourage investment and raise revenue; their effects remained contested.','Iván Duque'],
  ['The employment shock','Unemployment reached the highest point in this series. Having a wage also depends on keeping a job.','COVID-19 and lockdowns','The pandemic halted activity, destroyed jobs and required emergency spending. It was a global shock.','Iván Duque'],
  ['Recovery begins','Unemployment fell from 2020, but comparable informality remained close to six in every ten workers.','Reopening and recovery','Activity and employment rebounded, while informality and inequality persisted.','Iván Duque'],
  ['One million pesos','The minimum wage reached one million while annual inflation closed in double digits.','Global inflation and transition','Food, energy and supply chains pressured inflation. The year was shared by Duque and Petro.','Duque → Petro transition'],
  ['Wages respond','Nominal growth was strong, although prices were still rising rapidly.','Fuel adjustment and tax reform','The adjustment reduced the fuel fund deficit but increased transport costs.','Gustavo Petro'],
  ['Wages, rates and reforms','Formal incomes rise while credit, investment and informality still shape the result.','Wages, rates and reforms','Wage rises supported formal incomes while high rates slowed credit and investment.','Gustavo Petro'],
  ['Lower unemployment, persistent informality','Unemployment fell, but more than half of employed people remained in informal work.','Recovery with fiscal challenges','Consumption and services supported activity, while investment, informality and public finances remained challenges.','Gustavo Petro'],
  ['The present is still moving','Inflation and employment data are partial. This picture will change when the year closes.','Partial data and political change','The year is not over. Wages, inflation, rates, spending and expectations can still change the final result.','Gustavo Petro'],
] as const

const copy = {
  es: {
    nav: ['Historia','Datos','Metodología','Fuentes'], eyebrow:'Poder adquisitivo, explicado con algo cotidiano', title:'¿Cuántos Chocorramos compra un salario mínimo?', lede:'Una referencia pedagógica para comparar salario, precio e inflación. No reemplaza una canasta de consumo ni mide por sí sola el costo de vida.', start:'Empezar la historia', calculate:'Entender el cálculo', disclaimer:'Imagen usada únicamente como referencia visual del producto.', stats:['años comparados','dimensiones económicas','fuentes visibles'],
    storyEyebrow:'Una historia que cambia mientras bajas', storyTitle:'Un salario, muchos Chocorramos', storyIntro:'La comparación parte de dos precios ancla editables: $1.100 en 2016 y $3.500 en 2026. Son valores aportados para el ejercicio y todavía necesitan una fuente verificable.', warningTitle:'Dos preguntas diferentes:', warning:'el peso sí pierde poder adquisitivo cuando suben los precios. Sin embargo, un salario puede comprar más si aumenta más rápido que esos precios.', contextTitle:'Contexto no significa causalidad:', context:'cada año combina políticas nacionales, decisiones privadas y choques externos. La línea histórica ayuda a entender el entorno, no a asignar todo el resultado económico a un presidente.', sources:'Referencias de contexto:', selected:'Año seleccionado', anchor2016:'Ancla 2016', anchor2026:'Ancla 2026', salary:'Salario mínimo mensual', units:'Chocorramos hipotéticos por salario', usedPrice:'Precio usado:', estimated:'Precio estimado', anchor:'Ancla por verificar', inflation:'Inflación', unemployment:'Desempleo', informal:'Empleo informal', noData:'Sin dato comparable', fixed:'Poder de compra de $100.000 fijos', hypothetical:'Chocorramos hipotéticos', economicContext:'Contexto económico',
  },
  en: {
    nav: ['Story','Data','Methodology','Sources'], eyebrow:'Purchasing power, explained through something familiar', title:'How many Chocorramos can a minimum wage buy?', lede:'A teaching reference for comparing wages, prices and inflation. It does not replace a consumption basket or measure the cost of living by itself.', start:'Start the story', calculate:'Understand the calculation', disclaimer:'Product image used only as a visual reference.', stats:['years compared','economic dimensions','visible sources'],
    storyEyebrow:'A story that changes as you scroll', storyTitle:'One wage, many Chocorramos', storyIntro:'The comparison starts with two editable price anchors: $1,100 in 2016 and $3,500 in 2026. They are supplied assumptions and still require a verifiable source.', warningTitle:'Two different questions:', warning:'the peso loses purchasing power as prices rise. A wage can nevertheless buy more if it rises faster than those prices.', contextTitle:'Context is not causation:', context:'each year combines national policies, private decisions and external shocks. The timeline explains the setting; it does not assign the full economic result to one president.', sources:'Context references:', selected:'Selected year', anchor2016:'2016 anchor', anchor2026:'2026 anchor', salary:'Monthly minimum wage', units:'Hypothetical Chocorramos per wage', usedPrice:'Price used:', estimated:'Estimated price', anchor:'Anchor to verify', inflation:'Inflation', unemployment:'Unemployment', informal:'Informal employment', noData:'No comparable data', fixed:'Purchasing power of a fixed $100,000', hypothetical:'hypothetical Chocorramos', economicContext:'Economic context',
  },
} as const

export function originalStoryCopy(language: Language) {
  return { ...copy[language], steps: language === 'es' ? esSteps : enSteps }
}
